"""CLI for the Rerun Query API refine step (post-recording).

Examples::

    python -m p5_rerun_port.query_api_cli --dataset cans --schema
    python -m p5_rerun_port.query_api_cli --dataset cans --tag "Good episode"
    python -m p5_rerun_port.query_api_cli --dataset cans --episode episode_01 --entity follower/position
    python -m p5_rerun_port.query_api_cli --dataset cans --episode episode_01 --compare goal-vs-position
    python -m p5_rerun_port.query_api_cli --dataset cans --tag "Good episode" --report reports/cans_query.md
"""

from __future__ import annotations

import argparse
from pathlib import Path

from p5_rerun_port.constants import DEFAULT_CATALOG, DEFAULT_RECORDINGS_DIR, FOLLOWER
from p5_rerun_port.query_dataset import _print_table
from p5_rerun_port.rerun_query import (
    compare_goal_vs_position,
    episode_segment_identity,
    episodes_for_query,
    find_scalar_columns,
    list_schema,
    open_dataset_server,
    pick_timeline,
    reader_to_pandas,
    rrd_paths_for_records,
    schema_report,
    stack_scalar_column,
)


def _inspect_entity_via_query(
    dataset: str,
    entity: str,
    recordings_dir: Path,
    timeline: str | None,
    rrd_paths: list[Path],
) -> None:
    with open_dataset_server(
        dataset, recordings_dir=recordings_dir, rrd_paths=rrd_paths
    ) as ds:
        index = pick_timeline(ds, timeline)
        variants = [entity, entity.strip("/"), f"/{entity.strip('/')}"]
        view = ds.filter_contents(variants)
        df = reader_to_pandas(view, index=index)
        cols = find_scalar_columns(df, entity.strip("/")) or find_scalar_columns(df, f"/{entity.strip('/')}")
        print(f"Query API entity={entity!r} timeline={index!r} rows={len(df)}")
        if not cols:
            schema = list_schema(ds)
            print(f"no scalar columns matched; entities={schema['entities'][:24]}")
            print(f"columns={list(df.columns)[:24]}")
            return
        series = stack_scalar_column(df[cols[0]])
        if series is None:
            print("empty series")
            return
        import numpy as np

        print(f"frames={len(series)}  dim={series.shape[1] if series.ndim > 1 else 1}")
        print(f"first: {np.array2string(series[0], precision=2, suppress_small=True)}")
        print(f"last:  {np.array2string(series[-1], precision=2, suppress_small=True)}")
        print(f"mean:  {np.array2string(np.nanmean(series, axis=0), precision=2, suppress_small=True)}")


def _write_report(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote report: {path}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Rerun Query API over reBot .rrd recordings (post-record refine step)"
    )
    ap.add_argument("--dataset", required=True, help="Dataset folder name under recordings/")
    ap.add_argument("--tag", default=None)
    ap.add_argument("--episode", default=None)
    ap.add_argument("--entity", default=None, help=f"e.g. {FOLLOWER}/position")
    ap.add_argument(
        "--compare",
        choices=["goal-vs-position"],
        default=None,
        help="Run a Query API evaluation over aligned series",
    )
    ap.add_argument("--schema", action="store_true", help="Print dataset schema via Query API")
    ap.add_argument("--timeline", default=None, help="Timeline/index name for reader()")
    ap.add_argument("--report", type=Path, default=None, help="Write markdown report path")
    ap.add_argument("--recordings-dir", type=Path, default=DEFAULT_RECORDINGS_DIR)
    ap.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    args = ap.parse_args(argv)

    report_lines: list[str] = [
        f"# Rerun Query API report — `{args.dataset}`",
        "",
        "Generated by `python -m p5_rerun_port.query_api_cli`.",
        "",
    ]

    # Catalog table (metadata) — still useful; Query API uses the .rrd bodies
    rows = episodes_for_query(
        dataset=args.dataset,
        tag=args.tag,
        episode=args.episode,
        recordings_dir=args.recordings_dir,
        catalog_path=args.catalog,
    )
    if (args.episode or args.tag) and not rows:
        raise SystemExit("FAIL: no catalog episodes match the requested --episode/--tag filter")
    rrd_paths = rrd_paths_for_records(rows)
    verified_identity = (
        episode_segment_identity(rows[0]) if args.episode and len(rows) == 1 else None
    )
    print("=== catalog (local metadata) ===")
    _print_table(rows)
    report_lines.append("## Catalog episodes")
    report_lines.append("")
    if rows:
        report_lines.append("| dataset | episode | tag | frames | dur_s | task |")
        report_lines.append("|---|---|---|---:|---:|---|")
        for e in rows:
            report_lines.append(
                f"| {e.dataset} | {e.episode} | {e.tag} | {e.n_frames} | {e.duration_s:.1f} | {e.task} |"
            )
    else:
        report_lines.append("_No catalog rows selected._")
    report_lines.append("")

    if args.schema:
        print("=== Query API schema ===")
        text = schema_report(
            args.dataset, args.recordings_dir, rrd_paths=rrd_paths
        )
        print(text)
        report_lines.append("## Schema")
        report_lines.append("```")
        report_lines.append(text)
        report_lines.append("```")
        report_lines.append("")

    if args.entity:
        print("=== Query API entity series ===")
        _inspect_entity_via_query(
            args.dataset,
            args.entity,
            args.recordings_dir,
            args.timeline,
            rrd_paths,
        )
        report_lines.append(f"## Entity `{args.entity}`")
        report_lines.append("Inspected via `dataset.filter_contents(...).reader(...).to_pandas()`.")
        report_lines.append("")

    if args.compare == "goal-vs-position":
        print("=== Query API compare: goal vs position ===")
        with open_dataset_server(
            args.dataset, recordings_dir=args.recordings_dir, rrd_paths=rrd_paths
        ) as ds:
            result = compare_goal_vs_position(
                ds,
                episode=args.episode,
                timeline=args.timeline,
                verified_identity=verified_identity,
            )
        for line in result.summary_lines():
            print(line)
        report_lines.append("## Compare `follower/goal` vs `follower/position`")
        report_lines.append("")
        report_lines.append("```")
        report_lines.extend(result.summary_lines())
        report_lines.append("```")
        report_lines.append("")
        report_lines.append(
            "High mean/max error can mean teleop lag, dropped frames, or a bad take — "
            "use this to curate before `export_lerobot`."
        )

    if not args.schema and not args.entity and not args.compare:
        # Default: schema snapshot so a bare invoke still exercises Query API
        print("=== Query API schema (default) ===")
        text = schema_report(
            args.dataset, args.recordings_dir, rrd_paths=rrd_paths
        )
        print(text)
        report_lines.append("## Schema")
        report_lines.append("```")
        report_lines.append(text)
        report_lines.append("```")

    if args.report:
        _write_report(args.report, report_lines)

    print(
        "\nOK: Query API path used rr.server.Server + dataset.reader() "
        "(post-record only; does not open arms)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
